# Generated by Django 2.0.9 on 2018-11-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_present_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
