# Generated by Django 2.0.9 on 2018-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_board_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sound',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
