# Generated by Django 2.0.9 on 2018-11-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0008_script_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='title',
            field=models.CharField(max_length=100, null=True, default="__REMOVE__")
        ),
    ]
