# Generated by Django 2.0.9 on 2018-11-01 16:39

from django.db import migrations, models
from vople.users.models import User
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0010_board_model_add_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='joined_member',
        ),
        migrations.AddField(
            model_name='board',
            name='joined_member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, null=True),
        ),
    ]
