# Generated by Django 2.0.9 on 2018-11-01 16:39

from django.db import migrations, models
from vople.users.models import User
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0011_alter_board_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='joined_member',
        ),
        migrations.AddField(
            model_name='board',
            name='joined_member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='comment',
            field=models.ForeignKey(on_delete=models.DO_NOTHING, null=True, related_name="comment_plots", to='sounds.Comment'),
        ),
        migrations.AddField(
            model_name='plot',
            name='is_adjust',
            field=models.BooleanField(null=False, default=False),
        ),
        migrations.AddField(
            model_name='plot',
            name='roll_name',
            field=models.CharField(null=False, default="Roll_Name", max_length=80),
        ),
        migrations.AddField(
            model_name='plot',
            name='order',
            field=models.IntegerField(null=False)
        ),
    ]
