# Generated by Django 2.0.9 on 2018-11-01 16:39

from django.db import migrations, models
from vople.users.models import User
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_alter_plot_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(null=False, on_delete=django.db.models.deletion.DO_NOTHING, to='sounds.Script')),
                ('roll_name', models.CharField(max_length=20, null=False)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, related_name="my_casts")),
                ('is_adjust', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='plot',
            name='script',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='member',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='is_adjust',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='roll_name',
        ),
        migrations.AddField(
            model_name='plot',
            name='cast',
            field=models.ForeignKey(to='sounds.Cast', related_name="plots_by_cast", null=True, blank=True, on_delete=django.db.models.deletion.DO_NOTHING),
        ),
    ]
