# Generated by Django 2.0.9 on 2018-11-22 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0020_alter_second'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='present',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sounds.Present'),
        ),
        migrations.AlterField(
            model_name='casting',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_castings', to=settings.AUTH_USER_MODEL),
        ),
    ]